services:
  backend:
    build:
      context: ./back   # Use back directory as context
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    depends_on:
      - db
    restart: on-failure  # Automatically restart on failure

  front:
      build:
        context: ./front
        dockerfile: Dockerfile
      ports:
        - "4000:4000" # Expose frontend on port 4000
      depends_on:
        - backend
      restart: on-failure
    
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
