# Dockerfile in back/
# Use the official Node.js image as a base
FROM node:18-alpine

# Create and set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json, package-lock.json, and pnpm-lock.yaml files from back/
COPY package*.json ./
#COPY pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN pnpm run build

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]
