import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "CATMASH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className=".container">
          <div className="header">
            <Image src="/logo.png" alt="Cat Icon" width={40} height={40} className="logo" />
            <h1>CATMASH</h1>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
