# Use the lightweight Node.js image based on Alpine
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package configuration files
COPY package*.json ./


# Install pnpm globally and set configurations
RUN npm install -g pnpm@latest
RUN pnpm config set store-dir /root/.pnpm-store
RUN pnpm config set network-concurrency 2
RUN pnpm config set fetch-retries 2

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Set the environment variable for the port
ENV PORT 4000
ENV NODE_OPTIONS="--max-old-space-size=256"  

# Build the Next.js application
RUN pnpm run build

# Expose port 4000 for the frontend
EXPOSE 4000

# Start the Next.js application
CMD ["pnpm", "start"]
